"""Resize/compress voucher-type JPEGs and emit embeddable data URLs for the bundle."""
from __future__ import annotations

import base64
import io
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets" / "source"
OUT = ROOT / "src" / "generated" / "voucher-type-images.js"
TYPES = ("heartland", "supermarket")
MAX_WIDTH = 140
QUALITY = 52


def optimize(path: Path) -> tuple[bytes, tuple[int, int]]:
    with Image.open(path) as im:
        im = im.convert("RGB")
        w, h = im.size
        if w > MAX_WIDTH:
            nh = max(1, round(h * MAX_WIDTH / w))
            im = im.resize((MAX_WIDTH, nh), Image.Resampling.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, format="JPEG", quality=QUALITY, optimize=True)
        return buf.getvalue(), im.size


def main() -> int:
    lines = [
        "// Generated by scripts/optimize_images.py - do not edit.",
        "export const VOUCHER_TYPE_IMAGES = {",
    ]
    total = 0
    for name in TYPES:
        src = SOURCE / f"{name}.jpg"
        if not src.is_file():
            print(f"missing source image: {src}", file=sys.stderr)
            return 1
        data, size = optimize(src)
        total += len(data)
        b64 = base64.b64encode(data).decode("ascii")
        lines.append(f"  {name}: {{")
        lines.append(f'    src: "data:image/jpeg;base64,{b64}",')
        lines.append(f"    width: {size[0]},")
        lines.append(f"    height: {size[1]},")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({total:,} bytes JPEG payload)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
